### ISSUE TITLE
Dont work

### ISSUE THREAD

**Issue by 3zveruga** [Chiheb-Nexus/PoloniexWrapper#1]
![default](https://cloud.githubusercontent.com/assets/6505608/16297154/a20ea3ea-3940-11e6-98eb-e9443644e9a3.png)
как бороться

**Comment by Chiheb-Nexus** [comment]
Hi.
Thanks for opening the discussion.
Well, the script is working and supporting only Python3 or higher. I guess you're using Python2 and this is why you've this error. 
Also i may notice, PoloniexWrapper_cmd.py: Still in beta and if you run it you'll have a simulation of buying in a loop untill reaching the deposit amount  or the end of the sell book orders (more features will be added soon).
However, PoloniexApi.py, is a complete Poloniex API written in Python3, too, and you can use it alone for your apps or if you want to create your own trading script.

This, is the script in action:  

![poloniex_cmd_preview](https://cloud.githubusercontent.com/assets/9258106/16297893/af2a2650-392a-11e6-8ede-3639d40749bc.jpg)

**Comment by 3zveruga** [comment]
![default](https://cloud.githubusercontent.com/assets/6505608/16298617/68ae3ee2-3947-11e6-8fc3-fcdb3181dd55.png)

what I do not so

**Comment by 3zveruga** [comment]
sorry working.

**Comment by Chiheb-Nexus** [comment]
Very strange.
Can you tell me wich Python version do you have in your windows ? 

Otherwise, the same process is working on my machine with 3.3.4 
![selection_002](https://cloud.githubusercontent.com/assets/9258106/16298964/be74345c-392f-11e6-83d3-60029b2d0cd8.jpg)

**Comment by 3zveruga** [comment]
![default](https://cloud.githubusercontent.com/assets/6505608/16299018/2a57edf8-3949-11e6-8a4b-7d57149c49b0.png)

**Comment by 3zveruga** [comment]
![default](https://cloud.githubusercontent.com/assets/6505608/16299076/714660d2-3949-11e6-93b0-ea3c57852147.png)

**Comment by 3zveruga** [comment]
random starting

**Comment by 3zveruga** [comment]
after a set amount of error

**Comment by Chiheb-Nexus** [comment]
Can you please update to Python 3.4 or higher  and test the script again ?

**Comment by 3zveruga** [comment]
ок downloading now

2016-06-23 13:56 GMT+04:00 Chiheb notifications@github.com:

> Can you please update to Python 3.4 or higher and test the script again ?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/Chiheb-Nexus/PoloniexWrapper/issues/1#issuecomment-228003881,
> or mute the thread
> https://github.com/notifications/unsubscribe/AGNEiJe0KfK1dicIomJgnF4Du8VjSLmqks5qOlg-gaJpZM4I8lVK
> .

## 

С уважением Владимир Мусатов

**Comment by 3zveruga** [comment]
![default](https://cloud.githubusercontent.com/assets/6505608/16299435/53850100-394b-11e6-807c-8af1e33e34f3.png)
dont work(((

**Comment by Chiheb-Nexus** [comment]
Weird! 
I'm on Windows 7 32bit with Python 3.4 and everything is okay. 
Can you contact me on my Email ? 

Otherwise, look in windows: 
![untitled](https://cloud.githubusercontent.com/assets/9258106/16299575/5555440a-393b-11e6-960c-c26e607de1a2.png)

**Comment by 3zveruga** [comment]
ok
